## YAML Template.
---
name: 1. Pull request

on:
    pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Lint code
          uses: oxsecurity/megalinter/flavors/java@v7

        - name: Run Trivy vulnerability scanner in repo mode
          uses: aquasecurity/trivy-action@0.20.0
          with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'sarif'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL'
  
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: 'trivy-results.sarif'