name: release

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint code
        env:
          ENABLE_LINTERS: JAVA_CHECKSTYLE,YAML_PRETTIER,ACTION_ACTIONLINT
          PRINT_ALPACA: false
          IGNORE_GENERATED_FILES: true
          DISABLE_ERRORS: true
        uses: oxsecurity/megalinter/flavors/java@v7

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: 11.x
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: |
            **/pom.xml
      - run: mvn --batch-mode --update-snapshots verify
        working-directory: teleprompter

      - run: mkdir staging && cp target/*.jar staging/teleprompter-${{ github.ref_name }}.jar
        working-directory: teleprompter

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: teleprompter/staging
      
      - name: Release with Notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            teleprompter/staging/teleprompter-${{ github.ref_name }}.jar